
/**************************************************************
 *	
 *	gameSong, 8 bit, 11025Hz,
 *	1 channel, 2069120 bytes/channel
 *	Total Size: 1 * 2069120 + 4 (header) = 2069164 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jason\Desktop\gameSong.wav
 *	Time-stamp: Sun Nov 24 15:37:58 2019
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 2069120

extern const unsigned char gameSong[2069120];

#endif /* __GAMESONGH__ */
