
/**************************************************************
 *	
 *	jumpSound, 8 bit, 11025Hz,
 *	1 channel, 1664 bytes/channel
 *	Total Size: 1 * 1664 + 4 (header) = 1708 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jason\Desktop\jumpSound.wav
 *	Time-stamp: Tue Nov 26 14:38:02 2019
 *	
 **************************************************************/

#ifndef __JUMPSOUNDH__
#define __JUMPSOUNDH__

#define JUMPSOUNDFREQ 11025
#define JUMPSOUNDLEN 1664

extern const unsigned char jumpSound[1664];

#endif /* __JUMPSOUNDH__ */
