
/**************************************************************
 *	
 *	loseSound, 8 bit, 44100Hz,
 *	1 channel, 334538 bytes/channel
 *	Total Size: 1 * 334538 + 4 (header) = 334582 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jason\Desktop\M05_Test\loseSound.wav
 *	Time-stamp: Thu Dec 05 20:34:07 2019
 *	
 **************************************************************/

#ifndef __LOSESOUNDH__
#define __LOSESOUNDH__

#define LOSESOUNDFREQ 44100
#define LOSESOUNDLEN 334538

extern const unsigned char loseSound[334538];

#endif /* __LOSESOUNDH__ */
