
/**************************************************************
 *	
 *	startSong, 8 bit, 11025Hz,
 *	1 channel, 235123 bytes/channel
 *	Total Size: 1 * 235123 + 4 (header) = 235167 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jason\Desktop\startSong.wav
 *	Time-stamp: Sun Nov 24 15:17:26 2019
 *	
 **************************************************************/

#ifndef __STARTSONGH__
#define __STARTSONGH__

#define STARTSONGFREQ 11025
#define STARTSONGLEN 235123

extern const unsigned char startSong[235123];

#endif /* __STARTSONGH__ */
